=== sociocom/real_mednlp-eval/MedTxt.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT root (metadata,articles) >
<!--
- root
    - metadata
        - name … データセット名
        - dataset … training/test
        - language … ja/en
        - creator … 製作者＝SocioCom
        - version
        - release-date
        - origin … 配布元URL
    - articles
        - article [id, title]
            - (body) = テキストデータ；PRISMタグ含む
-->
<!ELEMENT metadata (name,dataset,language,creator,version,release-date,origin)>
    <!ELEMENT name (#PCDATA)*>
    <!ELEMENT dataset (#PCDATA)*>
    <!ELEMENT language (#PCDATA)*>
    <!ELEMENT creator (#PCDATA)*>
    <!ELEMENT version (#PCDATA)*>
    <!ELEMENT release-date (#PCDATA)*>
    <!ELEMENT origin (#PCDATA)*>

<!ELEMENT articles (article)*>
        <!ELEMENT article (#PCDATA|d|a|f|c|timex3|t-test|t-key|t-val|m-key|m-val|r|cc|p)*>
            <!ATTLIST article id CDATA #REQUIRED>
            <!ATTLIST article title CDATA #REQUIRED>

<!-- 病変・症状 (Diseases and symptoms)
<d certainty={“positive” or “suspicious” or “negative” or “general”}>‌...‌</d>‌
 ※certainty 省略可
    positive: その病変・症状が患者に実際に認められた場合
    suspicious: 患者がその病変・症状に該当するのではないかと疑われている場合(鑑別疾患*1として提案されているなど)
    negative: 患者についてその病変・症状の存在が否定された場合
    general: 患者に関係ない一般的な病変・症状に関する記述や，将来生じる可能性のある病変・症状を表現している場合
 ※誤字・脱字の訂正(correction 属性)‌ 省略可
 -->
<!ELEMENT d (#PCDATA)*>
    <!ATTLIST d certainty (positive|suspicious|negative|general) #IMPLIED>
    <!ATTLIST d correction CDATA #IMPLIED>

<!-- ‌臓器・部位 (Anatomical parts)
<a>‌. . . ‌</a>‌
 ※誤字・脱字の訂正(correction 属性)‌ 省略可
-->
<!ELEMENT a (#PCDATA)*>
    <!ATTLIST a correction CDATA #IMPLIED>

<!-- 特徴・尺度 (Features and measurements)‌
<f>‌. . . ‌</f>‌
 ※誤字・脱字の訂正(correction 属性)‌ 省略可
-->
<!ELEMENT f (#PCDATA)*>
    <!ATTLIST f correction CDATA #IMPLIED>

<!-- ‌変化 (Change)
<c>‌. . . ‌</c>‌
 ※誤字・脱字の訂正(correction 属性)‌ 省略可
-->
<!ELEMENT c (#PCDATA)*>
    <!ATTLIST c correction CDATA #IMPLIED>

<!-- 時間表現 (TIMEX3)‌
<TIMEX3 type=“{DATE, TIME, duration, SET, AGE, MED, MISC}”>‌...‌</TIMEX3>‌
 ※type 省略不可
    DATE: 日歴に焦点をあてた日付表現
    TIME: 一日のうちのある時点に焦点をあてた表現や不定の現在を表す「今」「現在」などの時刻表現
    duration: 時間軸上の両端ではなく期間全体を表すことに焦点をあてた期間表現
    SET: 複数の日付・時刻・期間に焦点をあてた頻度集合表現
    AGE: 年齢に関する表現
    MED:「術後」など医療に特徴的な時間表現
    MISC: 以上のどれにも該当しない場合
 ※誤字・脱字の訂正(correction 属性)‌ 省略可
-->
<!ELEMENT timex3 (#PCDATA)*>
    <!ATTLIST timex3 type (date|time|duration|set|age|med|misc) #REQUIRED>
    <!ATTLIST timex3 correction CDATA #IMPLIED>

<!-- 検査・問診 (Test)
 <t-test state=“{scheduled, executed, negated, other}”>‌...‌</t-test>‌ —検査・問診名
 ※state 省略不可
    scheduled: 今後予定している(記録に記載された時点では実施されていない)場合
    executed: すでに実施済みの場合
    negated: 中止など，実施しないことになった場合
    other: 上記以外の状態の場合
‌ ※誤字・脱字の訂正(correction 属性)‌ 省略可

<t-key (state=“{scheduled, executed, negated, other}”)>‌...‌</t-key>‌ —検査・問診項目 もしくは医学的指標名
 ※state 省略可
 ※誤字・脱字の訂正(correction 属性)‌ 省略可

‌<t-val>‌. . . ‌</t-val>‌ — 検査・問診結果もしくは医学的指標の値
 ※誤字・脱字の訂正(correction 属性)‌ 省略可
 -->
<!ELEMENT t-test (#PCDATA)*>
    <!ATTLIST t-test state (scheduled|executed|negated|other) #REQUIRED>
    <!ATTLIST t-test correction CDATA #IMPLIED>

<!ELEMENT t-key (#PCDATA)*>
    <!ATTLIST t-key state (scheduled|executed|negated|other) #IMPLIED>
    <!ATTLIST t-key correction CDATA #IMPLIED>

<!ELEMENT t-val (#PCDATA)*>
    <!ATTLIST t-val correction CDATA #IMPLIED>


<!--  薬品 (Medicine)
<m-key state=“{scheduled, executed, negated, other}”>‌...‌</m-key>‌ —薬品名
‌ ※state 省略不可
    scheduled: 今後投薬を予定している(記録に記載された時点で投薬されていない)場合
    executed: すでに投薬中の場合，
    negated: 中止など，投薬しないことになった場合
    other: 上記以外の状態の場合
 ※誤字・脱字の訂正(correction 属性)‌ 省略可

<m-val (state=“{scheduled, executed, negated, other}”)>‌...‌</m-val>‌ —薬品の値
 ※state 省略可
 ※誤字・脱字の訂正(correction 属性)‌ 省略可
-->
<!ELEMENT m-key (#PCDATA)*>
    <!ATTLIST m-key state (scheduled|executed|negated|other) #REQUIRED>
    <!ATTLIST m-key correction CDATA #IMPLIED>

<!ELEMENT m-val (#PCDATA)*>
    <!ATTLIST m-val state (scheduled|executed|negated|other) #IMPLIED>
    <!ATTLIST m-val correction CDATA #IMPLIED>

<!-- 治療 (Remedy)
<r state=“{scheduled, executed, negated, other}”>‌...‌</r>‌
‌ ※state 省略不可
    scheduled: 今後治療を予定している(記録に記載された時点で実施されていない)場合
    executed: すでに実施中の場合
    negated: 中止など，実施しないことになった場合
    other: 上記以外の状態の場合
 ※誤字・脱字の訂正(correction 属性)‌ 省略可
-->

<!ELEMENT r (#PCDATA)*>
    <!ATTLIST r state (scheduled|executed|negated|other) #REQUIRED>
    <!ATTLIST r correction CDATA #IMPLIED>

<!-- クリニカルコンテクスト (Clinical Context)
‌<cc state=“{scheduled, executed, negated, other}”>‌...‌</cc>‌
 ※state 省略不可
    scheduled: 今後予定している(記録に記載された時点では実施されていない)場合
    executed: すでに実施済みの場合
    negated: 中止など，実施しないことになった場合
    other: 上記以外の状態の場合
 ※誤字・脱字の訂正(correction 属性)‌ 省略可
-->
<!ELEMENT cc (#PCDATA)*>
    <!ATTLIST cc state (scheduled|executed|negated|other) #REQUIRED>
    <!ATTLIST cc correction CDATA #IMPLIED>

<!-- 保留 (Pending)
<p>...‌</p>
 ※誤字・脱字の訂正(correction 属性)‌ 省略可

-->
<!ELEMENT p (#PCDATA)*>
    <!ATTLIST p correction CDATA #IMPLIED>

<!--
            ＊＊＊ END ＊＊＊
-->

=== sociocom/real_mednlp-eval/MedTxt-RR-JA-test.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE root SYSTEM "MedTxt.dtd">
<root>
<metadata>
<name>MedTxt-RR</name>
<dataset>test</dataset>
<language>JA</language>
<creator>Sociocom</creator>
<version>1.0</version>
<release-date>2021-09-30</release-date>
<origin>https://sociocom.naist.jp/</origin>
</metadata>
<articles>
<article id="72" title="">
左肺尖部背側に境界不明瞭な腫瘤を認めます。サイズは不明です。ご指摘の肺癌と考えます。
腫瘤は肋間筋や左第2肋骨に明らかに浸潤しています。
また、腫瘤が接する第2胸椎椎体左側から左横突起にかけて表面不整を呈しており、椎体浸潤ありと考えます。
T因子はT4と考えます。
上肺野以上に中下肺野ではスライスが厚く、数mm程度のサイズの肺転移は拾い上げることができませんが、粗大な肺転移を疑う病変は指摘できません。
左鎖骨上窩リンパ節には病的サイズのリンパ節を多数認めます。
N因子はN3と考えます。
胸水貯留はありません。
肝や副腎は撮像範囲外であり、転移の評価はできません。
</article>
<article id="73" title="">
左肺上葉に48mmの腫瘤影を認め、ご指摘の肺癌と考えます。明かな胸膜浸潤はなくT2b相当です。
＃5リンパ節は腫大し、形態もroundであり、転移リンパ節と考えます。N2相当です。
</article>
<article id="74" title="">
左肺尖部に大きな腫瘤を認めます。腫瘤は胸壁浸潤し、左第2肋骨にも浸潤しています。Pancorst腫瘍を疑います。左鎖骨上窩リンパ節も腫脹しており、リンパ節転移があるようです。
縦隔、肺門、腋窩などに病的リンパ節腫大は認めません。
心拡大ありません。
胸水みられません。
その他、観察範囲内に明らかな異常を指摘できません。
</article>
<article id="75" title="">
左肺上葉に境界明瞭な約4cmの腫瘤性病変を認めます。内部に含気はほとんど認められません。
充実性部分の辺縁にはすりガラス陰影があり、スピキュラ、胸膜ひきつれ像なども認めます。原発性肺癌を疑います。同側及び対側肺内に結節影は指摘できません。転移性肺腫瘍を疑うような所見はありません。
肺門、縦隔に有意なリンパ節腫大は指摘できません。リンパ節転移を疑うような所見はありません。
胸水は認められません。胸膜播種を疑うような所見は指摘できません。
T2aN0程度であり、遠隔転移がなければ外科的治療の適応と思われます
</article>
<article id="76" title="">
左肺上葉を中心として腫瘤性病変を認めます。左肺上葉の気管支の含気は消失、腫瘍による気管支閉塞を認めます。このため、左肺上葉はほぼ無気肺状態となり、腫瘍の正確な進展範囲は不明瞭です。左肺下葉にも一部、腫瘍の浸潤がみられます。左肺下葉の気管支は保たれており、左肺下葉の含気は保たれています。
左胸水が大量に貯留しています。胸膜播種の疑いがあります。
縦隔に大、小多数の腫大が見られ、縦隔リンパ節転移を疑います。
第7胸椎の椎体周囲軟部陰影が進展しています。縦隔浸潤を疑います。
右肺下葉S7に結節影を認めます。また、左第6肋骨に骨硬化性陰影を認めます。これらは4週間前のCTでは指摘することができず、新たに生じた病変のようです。右肺転移、左第6肋骨転移を疑います。
甲状腺両葉に腫瘤性病変を認めますが、これらは以前から変化がみられず、転移性病変ではなさそうです。
</article>
<article id="77" title="">
左上葉肺門部には異常造影効果を有する不整形腫瘤が認められ、既知の肺癌部分と思われます。気管支は閉塞し、左上葉無気肺を呈しているものと思われます。縦隔へも直接浸潤している可能性があります(T4)。
右肺下葉には前回認められなかった不整形結節が出現しており、転移が否定できません。
左胸水が目立ち、受動性無気肺を伴っています。胸膜面に造影される結節は判然としませんが、胸膜播種の可能性は除外しきれません。
同側縦隔や上縦隔には病的腫大したリンパ節が複数認められ、転移が示唆されます(N2)。
肝に低吸収腫瘤、右副腎に結節性病変、左第６肋骨に硬化像が新たに出現しています。いずれも新規病変であり、一元的に転移の可能性が考えられます(M1c)。
右中葉には炎症瘢痕と思われる索状影を認めます。
甲状腺右葉優位の腫瘤性病変は過去画像と著変ありません。超音波ともあわせて性状フォローください。
</article>
<article id="78" title="">
左上葉には不均一な増強効果を有する不整形腫瘤が認められ、気管支閉塞とともに無気肺を呈しています。ご指摘の肺癌部分と思われます。内部は嚢胞変性や液体貯留を伴っているものと考えます。
左房内には⻑径85mm程度の造影欠損が認められ、腫瘍の直接浸潤が示唆されます(T4)。
右肺尖部には石灰化を伴った不整形結節が認められ、既知の結核に伴う変化でしょうか。
また両側中下肺野には不整形陰影やすりガラス影が散見されます。これらは炎症性変化、転移、いずれも鑑別に挙がります(転移とするならM1a)。臨床所見、検査所見とも総合してご評価ください。
縦隔に病的リンパ節腫大認めません。
有意な胸水認めません。
撮像範囲の肝、副腎に明らかな腫瘤は指摘できません。
</article>
<article id="79" title="">
右上葉縦隔側に腫瘤性病変を認め肺癌が疑われます。右上葉気管支は腫瘤により閉塞しており、上葉は無気肺となっています。腫瘤は縦隔と広く接し、一部突出したような形態となっています。縦隔浸潤の可能性があります。
明らかな肺内転移は指摘できません。
縦隔や肺門に有意なリンパ節腫大は指摘できません。
胸水はありません。
両腎嚢胞を認めます。
</article>
<article id="80" title="">
右肺上葉に巨大な腫瘤性病変があり、末梢にも浸潤があります。無気肺を伴っているようです。
縦隔胸膜と広く接し、近傍の脂肪織濃度も上昇しています。
縦隔浸潤ありと考えます。
上大静脈の浸潤は指摘出来ません。
右上葉気管支も腫瘤により狭窄しています。浸潤と考えます。
右気管支、気管も浸潤しているようです。
リンパ節転移は指摘出来ません。
以上よりT4相当と考えます。
</article>
<article id="81" title="">
左肺上葉に境界明瞭な腫瘤影を認めます。辺縁はやや不整でスピクラ様の毛羽立ちを伴っています。既知の肺癌と考えます。長径は40mmです。葉間胸膜のわずかな引き込みがみられますが、胸膜浸潤はないと考えます。
この腫瘤の腹側に小結節を認めます。造影後の画像しかありませんので、造影効果は判断できませんが、同一肺葉内転移を疑います。
T因子はT3と考えられます。
その他の肺野には肺転移を疑う病変は指摘できません。
縦隔・肺門リンパ節に病的腫大は認めません。N因子はN0と考えます。
胸水貯留はありません。
強く骨転移を疑うような骨破壊や腫瘤性病変は認めません。
他のM因子は判断できず、MXです。
</article>
<article id="82" title="">
左肺上葉気管支は途絶し、肺門部から末梢にかけて広範囲に腫瘍を認めます。肺門部肺癌および随伴性の無気肺を疑います。腫瘤は左肺門部リンパ節と一塊となっているようです。
左胸水は中等度貯留しています。
肝内に低吸収腫瘤を認めており、肝転移を疑います。
左副腎内にも腫瘤を認めており、副腎転移を疑う所見です。
甲状腺右葉の結節は以前のCTでも見られており、著変ありません。良性結節を疑います。
心拡大みられません。
その他、観察範囲内に明らかな異常を指摘できません
</article>
<article id="83" title="">
右上葉には縦隔に広く接する腫瘤性病変が認められます。ご指摘の肺癌部分と思われます。
縦隔浸潤が疑われますが、明らかな上大静脈浸潤は指摘できません(T4)。右上葉枝はこれにより狭窄し、上葉無気肺を呈しています。
その他肺野に明らかな異常陰影指摘できません。
縦隔右側のリンパ節は腫瘍と一塊となって増大している可能性は否定できません。
有意な胸水認めません。
肝、副腎に明らかな転移は指摘できません。
腎嚢胞を認めます。
</article>
<article id="84" title="">
【胸部造影CT】
右上葉気管⽀を閉塞する不整形な腫瘤がみられ，肺癌が疑われます。無気肺を⽣じています。
腫瘤は分葉状であり，気管⽀周囲にリンパ節転移が存在して⼀体となっている可能性もあります。
また腫瘤は縦隔に広く接しており，浸潤が疑われます。上⼤静脈は変形していますが，浸潤は明らかではありません。⾎栓は明らかではありません。
肝，副腎，⾻には明らかな転移を認めません。
副脾，両腎嚢胞を認めます。
</article>
<article id="85" title="">
右肺下葉の中枢側に主座を置く、腫瘤性病変を認めます。原発性肺癌を疑います。病変は長径55mmであり、肺門部に連続しています。腫瘍の末梢側は含気が消失、無気肺となっています。
同側および対側肺に結節影は指摘できません。肺内転移を疑う所見は指摘できません。
右肺門から縦隔にかけて、多数の結節を認めます。いずれもリンパ節腫大を疑います。リンパ節転移の混在の可能性が高いと思います。
</article>
<article id="86" title="">
左肺上葉に正常肺実質を置換する巨大な腫瘤性病変を認め、既知の肺癌と考えます。
病変は左肺動脈、左房内に浸潤しています。対側縦隔、同側縦隔リンパ節腫大を認め、転移リンパ節を疑います。
両側肺に多発結節影、浸潤影があり、多発肺内転移、肺炎の可能性があります。
縦隔胸膜にも浸潤している可能性があります。
右副腎は腫大し、副腎転移と考えます。
以上より、肺癌cT4N3M1bと考えます。
</article>
<article id="87" title="">
右肺下葉気管支は閉塞しており、同部位に55mm大の腫瘤を認めます。造影CTでやや弱い濃染を認めます。その末梢は無気肺を呈しています。肺門部肺癌（T3）を疑います。
気管分岐下リンパ節に腫大したリンパ節を認めており、リンパ節転移を疑います。N2と思われます。
心拡大みられません。
胸水みられません。
その他、観察範囲内に明らかな異常を指摘できません。
</article>
<article id="88" title="">
左上葉背側に軟部腫瘤を認め肺癌が疑われます。胸膜と広く接しており浸潤が疑われます。左第2肋骨にも破壊像を伴っており浸潤の可能性があります。
明らかな肺内転移は指摘できません。
両下葉に炎症瘢痕を疑う索状影を認めます。
左鎖骨上窩に腫大リンパ節を認め転移が疑われます。
胸水はありません。
</article>
<article id="89" title="">
左上葉気管支内に腫瘤が充満し左上葉は無気肺となっています。肺癌が疑われます。
右下葉縦隔側に結節影を認めます。炎症性変化かもしれませんが、転移の可能性もあります。
同側縦隔に腫大リンパ節を散見し転移が疑われます。
左胸水を認めます。明らかな播種結節は指摘できませんが、胸膜播種にはご留意ください。
左第6肋骨に硬化像を認め転移が疑われます。
甲状腺に低吸収腫瘤を認めます。腺腫などで矛盾しません。
肝に淡い低吸収域を認め転移の可能性があります。USでもご確認ください。
右副腎に結節を認めこちらも転移の可能性があります。
</article>
<article id="90" title="">
右下葉縦隔側に径55mm大の軟部腫瘤を認め肺癌が疑われます。腫瘤により右下葉気管支は閉塞し、右下葉は無気肺となっています。
その他の肺野に明らかな異常陰影は指摘できません。
右肺門部に腫瘤と一塊となった腫大リンパ節を認め転移が疑われます。縦隔にも軽度腫大リンパ節を散見します。反応性でも矛盾しないサイズですが、転移も否定できないためPETでもご確認ください。
胸水はありません。
</article>
<article id="91" title="">
4週間前のCTと比較しました。
左上葉無気肺を認めます。左上葉気管支は閉塞しており左上葉気管支近位部周囲には肺癌を疑う腫瘤が認められます。左上肺静脈末梢側に浸潤しています。
左肺門部リンパ節腫大と一塊となっているようです。右下葉には2個のいずれも⻑径7mmの結節を認めます。前回のCTではこの結節は指摘できず、副腫瘍結節が疑われます。
左肺門部リンパ節、#5,#6リンパ節が腫大しており、リンパ節転移を疑います。N分類でN2相当と思われます。
左胸水貯留が出現しています。明らかな播種結節を認めませんが悪性胸水の可能性が疑われます。
甲状腺右葉に⻑径80mmの腫瘤を認めます。左葉にも小さな低吸収結節を認めます。いずれも質的診断はCTでは困難です。USでも併せて評価をお願いします。
左第6肋骨に径13mmの硬化性腫瘤性病変が出現しており、肋骨転移を疑います。右副腎に径14mmの低吸収結節、肝にも結節が出現しており転移が疑われます。M分類でM1c相当と思われます。
</article>
<article id="92" title="">
左肺上葉肺尖部付近に境界明瞭な腫瘤性病変を認めます。内部に含気は認められず、充実性腫瘍であり、原発性肺癌を疑います。背側では胸壁に浸潤を認めます。第２肋骨にも溶解像を認めます。いわゆるPancoast腫瘍です。
肺に結節影を指摘できません。肺転移を疑うような所見は認めません。
縦隔、肺門、腋窩などに病的リンパ節腫大は認めません。リンパ節転移を疑う様な病変は指摘できません。
</article>
<article id="93" title="">
左上葉に径40mm大の腫瘤影を認め、spiculaや胸膜嵌入像を伴っています。肺癌が疑われます。
明らかな肺内転移は指摘できません。
縦隔や肺門に有意なリンパ節腫大は指摘できません。
胸水はありません。
</article>
<article id="94" title="">
左舌区S4に⻑径48mm大の不整な分葉状腫瘤が認められます。spiculaが目立ち、下方では葉間胸膜を超えた進展が疑われます。T2bの肺癌が疑われます。
その他肺野に粗大な腫瘤や浸潤影は指摘できません。
大動脈下リンパ節は最大短径10mm未満で、明らかな病的腫大とは言えません(読影者註：⻑径10mmとの設定ですので、短径は10mm未満としています)。
有意な胸水認めません。
</article>
<article id="95" title="">
【胸部造影CT】
左肺上葉を占拠する分葉状の不整形な腫瘤があり，左肺上葉は無気肺に陥っています。
右肺⾨部リンパ節，気管分岐下リンパ節も腫⼤しています。
以上からは肺癌およびリンパ節転移が疑われ，左肺⾨部リンパ節とは⼀塊となっているものと思われます。
腫瘤は縦隔や胸膜に広く接しており，浸潤が疑われます。
また，この腫瘤から連続して左房内に不整形腫瘤がみられ，左房内への進展も疑われます。
さらに，両肺末梢側には限局性浸潤影やfeeding-vesselsignを伴う多発結節影もみられ，多発肺内転移の可能性もあります。
肝，副腎，⾻には撮像内で腫瘤を認めません。
肺気腫を認めます。
右肺尖部には縮⼩傾向・気管⽀拡張・⼩⽯灰化を伴う索状影があり，過去の抗酸菌感染などによる陳旧性変化と考えます。
</article>
<article id="96" title="">
右肺⾨部に⻑径55mm⼤の不整形の腫瘤があり，既知の肺癌と考えます。
右下葉気管⽀の⼀部（B6，B9，B10）を閉塞しており，右肺下葉S6，S9，S10は無気肺に陥っています。また，右肺⾨部リンパ節が腫⼤しており，原発巣と⼀塊となったリンパ節転移と考えます。
肝，副腎，⾻には転移を認めません。
</article>
<article id="97" title="">
左肺上葉気管支は根部で途絶し、左肺上葉は全体が多房状の腫瘤で置換されています。既知の肺癌と考えます。胸壁への浸潤所見はありません。
上記肺癌に連続するように、左心房内に長径85mmの腫瘤を認めます。辺縁がわずかに造影されているようですが、内部はほぼ造影されていません。左肺上葉の腫瘤と性状が似ており、腫瘍浸潤と考えます。T因子はT4と考えます。
両側肺野には濃いすりガラス影や浸潤影、不整形結節が多発しています。これらはいずれも転移を疑います。
両側肺尖部には陳旧性結核を疑う、石灰化を伴う胸膜肥厚を認めます。
両側肺門部や縦隔には病的腫大リンパ節を認め、N因子はN3と考えます。
少量の両側胸水貯留を認めます。
胸膜播種を疑う結節は認めません。
右副腎に乏血性腫瘤を認めます。転移の可能性が高いと考えます。
撮像範囲に強く骨転移を疑う骨破壊や腫瘤影は認めません。
その他の遠隔転移は指摘できません。
</article>
<article id="98" title="">
右肺下葉に浸潤影を認めます。中枢側に腫瘤性病変があり、無気肺も合併しているようです。
病変のサイズは55mmで、大血管への明かな浸潤は指摘出来ません。T3相当と考えます。
＃11i,#7,#8リンパ節腫大を認め、転移リンパ節と考えます。N2相当です。
</article>
<article id="99" title="">
4週間前のCTと比較しました。
左肺門部には約○×○cm大の淡く増強される境界不明瞭な軟部影を認め、左肺門リンパ節と一塊となっています。左肺上葉は無気肺を呈し、舌区の気管支に僅かに含気を認めるのみとなっています。無気肺となった左肺上葉内には不均一な増強効果を認めており、経気道的な進展をきたした腫瘍の増強を見ているものと思われます(cT?※T因子は上記○cmの計測で判断)。
右肺下葉内側には小結節が新たに出現しており、経過を併せ、転移を疑います。
大動脈傍や大動脈下の複数の縦隔リンパ節腫大は転移を疑います(cN2)。またTh6・7傍椎体には腫瘤を認め、また左第6肋骨には新たな膨隆性の骨硬化像が出現しています。
他にも肝内に新たな低吸収域、右副腎結節の出現あり、短期間での経過の病勢の増悪(転移)が示唆されます(M1c)。
右肺中葉や左肺舌区には陳旧性炎症性変化を疑う線状索状影を認めます。
左胸水を認めます。
甲状腺右葉の腫瘤や左葉の低吸収結節は以前のCTと著変ありません。
Impression(記載箇所あれば)：
左肺門部肺癌−左上葉無気肺(cT?N2M1c、気道内に沿った腫瘍進展を疑う)、多発転移(右肺下葉、肝、右副腎、Th6-7傍椎体、左第6肋骨)
甲状腺腫瘤・結節：前回同様
</article>
<article id="100" title="">
左肺上区から舌区に跨がる⻑径48mm大の不整形腫瘤を認め、周囲にspiculationを伴っていますx。病変は葉間裂に接していますが、左肺下葉への明らかな浸潤は指摘できません。明らかな副結節も見られません(cT2b)。
左肺門リンパ節の腫大を認め、転移を疑います。大動脈下の縦隔リンパ節(⻑径1cm)は有意な腫大ではないものの目立ち、リンパ節転移が否定できません(cN1以上)。FDG-PETでも御評価下さい。
その他、肺・縦隔に特記所見ありません。胸水は認めません。
撮像内の腹部に特記所見ありません。
Impression(記載箇所あれば)：左上葉肺癌(cT2bN1≧MX)疑い
</article>
<article id="101" title="">
両肺には中等度の気腫性変化を認めます。
右肺下葉肺門側には⻑径約5.5cm大の増強効果に乏しい腫瘤を認め、末梢には閉塞性無気肺と粘液栓を疑う増強不良域を認めます(cT3)。腫瘍により右肺動脈下葉枝は縦隔側よりで閉塞し、avascularな状態となっています。気管支動脈の流入を認めます。
右肺門や気管分岐下の縦隔リンパ節は腫大しており、転移が否定できません(N1以上)。FDG-PETを追加されて下さい。
その他、肺・縦隔に特記所見ありません。胸水はありません。
女性化乳房を認めます。
Impression(記載箇所あれば)：右肺門部肺癌(cT3N1≧MX)：末梢の閉塞性無気肺
</article>
<article id="102" title="">
左上葉S1+2に⻑径40mmの葉間胸膜陥凹を伴う分葉状の腫瘤を認めます。葉間胸膜浸潤が疑われます。
内部には気管支透亮像を伴っており辺縁部にはspiculaを伴っています。原発性肺癌が疑われます。T分類でT2相当と思われます。
肺野には副腫瘍結節を疑う病変を指摘できません。
鎖骨上窩、肺門部、縦隔に転移を疑うような類円形のリンパ節腫大を指摘できません。
心拡大、軽度の心嚢液貯留を認めます。
胸水貯留を認めません。
肝の濃度はやや低下しており脂肪肝を疑います。そのほか、撮像範囲の上腹部臓器に有意な異常を指摘できません。
</article>
<article id="103" title="">
左肺門部には左肺門のリンパ節と一塊となった増強効果の乏しい⻑径8.5cm大の腫瘤を認め、左肺上区・舌区は閉塞性無気肺を呈しています。また腫瘤は縦隔左側および左心房内(〜僅かに左心室内)、および左肺静脈内に進展しています(cT4)。生検結果と併せ、左肺門部肺癌の局所浸潤として合致しますが、鑑別に心臓原発の肉腫や肺静脈内発生の血管肉腫も挙がります。
両肺の複数の結節は肺転移、両肺下葉末梢の細気管支周囲のconsolidationは肺うっ血や肺炎の混在を疑います(M1a)。
両肺尖部の石灰化は陳旧性結核を疑います。
両側肺門や気管分岐下の縦隔リンパ節は腫大が見られ、転移を疑います(cN3)。両側少量胸水を認めます。
右副腎には低吸収腫瘤が疑われ、腺腫や楔状の形態からは過形成などを疑いますが、転移も否定できず、経過観察をされて下さい。
その他、撮像内の腹部に特記所見ありません。
Impression(記載箇所あれば)：左肺門部肺癌(cT4N3M1a)−左心房浸潤、多発肺転移
両肺下葉のconsolidation(肺うっ血肺炎)
右副腎結節(腺腫or過形成＞副腎転移)
</article>
<article id="104" title="">
左肺尖部には○×○cm大(一応の径を記載する)の不整形の肺内腫瘤を認め、肺癌を疑います。腫瘍は壁側胸膜を越え、左第2肋骨への浸潤を疑います(cT3)。左第1肋骨〜Th1椎体周囲の状態、左第3肋骨への浸潤の有無に関してはFDG-PETあるいは造影MRIで御評価下さい。
肺門・縦隔リンパ節の腫大は認めませんが、左鎖骨上窩や腋窩のリンパ節は複数腫大しており、左鎖骨上窩リンパ節は転移(cN3)、腋窩リンパ節も転移の可能性があります。
その他、撮像内で特記所見ありません。
Impression(記載箇所あれば)：左肺尖部肺癌(cT3N3MX)−左腋窩リンパ節腫大は転移の可能性あり
